# -*- coding: utf-8 -*-
"""CBIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102wG4U6HLkxiA1RC9G7Yjc9djF-ozM_J
"""

#bikin akses ke Gdrive
from google.colab import drive
drive.mount('/content/drive')

#ekstrak dataset
import zipfile
dataset_path = '/content/drive/MyDrive/CBIR/CarsDataset.zip'
extract_path = '/content/dataset'

with zipfile.ZipFile(dataset_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

#___Main Code___#
!pip install opencv-python scikit-image matplotlib

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
from skimage.feature import graycomatrix, graycoprops
from scipy.spatial.distance import cosine
import time
from google.colab import drive
import ipywidgets as widgets
from IPython.display import display, clear_output
from PIL import Image


class CBIR_Vehicle:
  def __init__(self, dataset_path):
    self.dataset_path = dataset_path
    self.features = []
    self.image_paths = []

  def extract_features(self, img):
    #img = cv2.resize(img, (256, 256))

#fitur warna : Histogram HSV
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hist_hsv = cv2.calcHist([hsv], [1, 1, 1], None, [5, 5, 5], [0, 256, 0, 256, 0, 256])
    hist_hsv = cv2.normalize(hist_hsv, hist_hsv).flatten()


#fitur tekstur : GLCM
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) #ubah jadi grayscale
    glcm = graycomatrix(gray, distances=[1], angles=[0], symmetric=True, normed=True)
    contrast = graycoprops(glcm, 'contrast')[0,0]
    energy = graycoprops(glcm, 'energy')[0,0]
    homogeneity = graycoprops(glcm, 'homogeneity')[0,0]
    texture_features = np.array([contrast, energy, homogeneity])

#fitur bentuk : Hu Moments
    moments = cv2.moments(gray)
    hu_moments = cv2.HuMoments(moments).flatten()
    return np.hstack([hist_hsv, texture_features, hu_moments])

#bikin database
  def build_database(self):
    print ("bikin database")
    start_time = time.time()
    for root, _, files in os.walk(self.dataset_path):
     for files in files:
       if files.lower().endswith(('.jpg', '.jpeg', '.png')):
        path = os.path.join(root, files)
        img = cv2.imread(path)
        if img is not None:
            features = self.extract_features(img)
            self.features.append(features)
            self.image_paths.append(path)
    self.features = np.array(self.features)
    print(f"Database selesai... {len(self.features)} gambar diproses")
    print(f"waktu eksekusi: {time.time() - start_time:.2f} detik")

#simpan datsbase
    print("menyimpan database")
    np.save("dataset.npy", self.features)
    np.save("paths.npy",self.image_paths)

  def load_database(self):
    print("loading database..")
    self.features = np.load("dataset.npy")
    self.image_paths = np.load("paths.npy")
    print(f"Database berhasil Dimuat {len(self.features)} Gambar Wes Ready")

  def query(self, query_img_path, top_k=3):
    query_img = cv2.imread(query_img_path)
    if query_img is None:
       print(f"Error gaiss gabisangebaca gambar {query_img_path}")
       return[]

    query_features = self.extract_features(query_img)

#hitung jarak cosine
    print("menghitung jarak cosine")
    distance = [cosine(query_features, feat) for feat in self.features]

#urutkan hasil
    print("mengurutkan hasil")
    sorted_indicies = np.argsort(distance)
    return [self.image_paths[i] for i in sorted_indicies[:top_k]]

  def show_results(self, query_path, results):
     if not results:
      print("Tidak ada Hasil Ditemukan")
      return
     plt.figure(figsize=(15, 5))

     #tampilin query
     query_img = cv2.cvtColor(cv2.imread(query_path), cv2.COLOR_BGR2RGB)
     plt.subplot(1, len(results)+1, 1)
     plt.imshow(query_img)
     plt.title("Query Image")
     plt.axis('off')

        # Tampilkan hasil
     for i, path in enumerate(results):
            img = cv2.cvtColor(cv2.imread(path), cv2.COLOR_BGR2RGB)
            plt.subplot(1, len(results)+1, i+2)
            plt.imshow(img)
            plt.title(f"Rank {i+1}")
            plt.axis('off')

     plt.tight_layout()
     plt.show()

# Main
if __name__ == "__main__":
   
    dataset_path = "/content/dataset/Cars Dataset"  # Hasil ekstraksi ZIP
    cbir = CBIR_Vehicle(dataset_path)

    # akses database
    try:
        print("Memuat database...")
        cbir.load_database()
    except:
        print("Membangun database pertama kali...")
        cbir.build_database()

# UI buat milih query
    # Dropdown berisi path gambar
    dropdown = widgets.Dropdown(
    options=cbir.image_paths,
    description='Pilih Gambar:',
    layout=widgets.Layout(width='800px')
    )

    # Output area 
    thumbnail_output = widgets.Output()

    # Tampilkan gambar thumbnail 
    def on_dropdown_change(change):
        if change['type'] == 'change' and change['name'] == 'value':
            img_path = change['new']
            img = cv2.imread(img_path)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            pil_img = Image.fromarray(img)
            pil_img.thumbnail((200, 200))  # ukuran thumbnail
            with thumbnail_output:
                clear_output(wait=True)
                display(pil_img)

    dropdown.observe(on_dropdown_change)

    # Tombol eksekusi
    search_button = widgets.Button(description="Cari Gambar Mirip")
    result_output = widgets.Output()

    def on_search_clicked(b):
        with result_output:
            clear_output(wait=True)
            query_path = dropdown.value
            print(f"Query image: {query_path}")
            results = cbir.query(query_path, top_k=10)
            cbir.show_results(query_path, results)


    search_button.on_click(on_search_clicked)

    # Tampilkan UI
    display(dropdown)
    display(thumbnail_output)
    display(search_button)
    display(result_output)




    # end..